# Generated by Django 3.0.3 on 2020-03-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='learn_time',
            new_name='learn_times',
        ),
    ]
