# Generated by Django 3.0.3 on 2020-03-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_is_classics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(default='街舞', max_length=20, verbose_name='课程类别'),
        ),
    ]
