# Generated by Django 3.0.3 on 2020-03-19 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursetag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetag',
            options={'verbose_name': '课程标签', 'verbose_name_plural': '课程标签'},
        ),
    ]
