# Generated by Django 3.0.3 on 2020-03-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200319_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetag',
            name='tag',
            field=models.CharField(max_length=100, verbose_name='标签'),
        ),
    ]
