# Generated by Django 3.0.3 on 2020-03-27 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20200327_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeLay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('age', models.CharField(max_length=20, verbose_name='年龄段')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
            ],
            options={
                'verbose_name': '年龄段',
                'verbose_name_plural': '年龄段',
            },
        ),
    ]
