# Generated by Django 3.0.3 on 2020-03-27 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_agelay'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='age',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='courses.AgeLay', verbose_name='年龄段'),
        ),
        migrations.AlterField(
            model_name='agelay',
            name='age',
            field=models.CharField(default=10, max_length=20, verbose_name='年龄段'),
        ),
    ]
