# Generated by Django 3.0.3 on 2020-03-28 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20200327_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.AgeLay', verbose_name='年龄段'),
        ),
    ]
