# Generated by Django 3.0.3 on 2020-04-03 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0015_auto_20200328_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestudent',
            name='detail',
            field=models.CharField(default='无', max_length=200, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='coursestudent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
