# Generated by Django 3.0.3 on 2020-04-16 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20200403_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='上课时间'),
        ),
        migrations.AddField(
            model_name='coursestudent',
            name='teacher_name',
            field=models.CharField(default='老师', max_length=20, unique=True, verbose_name='老师名称'),
        ),
    ]
