# Generated by Django 3.0.3 on 2020-04-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20200416_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('ds', 'URBAN DANCE(都市编舞)'), ('js', 'JAZZ(爵士舞)'), ('zy', 'HIPHOP(自由传统街舞)'), ('jx', 'POPPING(机械舞 震感舞)')], max_length=20, verbose_name='舞的种类'),
        ),
    ]
