# Generated by Django 3.0.3 on 2020-04-25 04:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0011_auto_20200425_0415'),
        ('operations', '0005_usercardorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('coursecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseCard', verbose_name='课卡')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户课卡',
                'verbose_name_plural': '用户课卡',
            },
        ),
    ]
