# Generated by Django 3.0.3 on 2020-03-22 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20200322_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseorg',
            options={'verbose_name': '培训机构', 'verbose_name_plural': '培训机构'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '老师', 'verbose_name_plural': '老师'},
        ),
    ]
