# Generated by Django 3.0.3 on 2020-04-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20200417_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='points',
            field=models.CharField(max_length=600, verbose_name='经历'),
        ),
    ]
