# Generated by Django 3.0.3 on 2020-04-23 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20200417_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jchf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('title', models.CharField(max_length=25, verbose_name='回放标题')),
                ('desc', models.CharField(max_length=100, verbose_name='回放描述')),
                ('url', models.CharField(max_length=1000, verbose_name='访问地址')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
            ],
            options={
                'verbose_name': '精彩回放',
                'verbose_name_plural': '精彩回放',
            },
        ),
    ]
