# Generated by Django 3.0.3 on 2020-04-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_jchf'),
    ]

    operations = [
        migrations.AddField(
            model_name='jchf',
            name='image',
            field=models.ImageField(max_length=200, null=True, upload_to='org/jchf/%Y/%m', verbose_name='封面'),
        ),
    ]
