# Generated by Django 3.0.3 on 2020-04-24 18:41

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_jchf_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('title', models.CharField(max_length=25, verbose_name='回放标题')),
                ('image', models.ImageField(max_length=200, null=True, upload_to='org/n/%Y/%m', verbose_name='封面')),
                ('desc', DjangoUeditor.models.UEditorField(default='', verbose_name='描述')),
            ],
            options={
                'verbose_name': '网站通知',
                'verbose_name_plural': '网站通知',
            },
        ),
    ]
